# Generated by Django 5.2.5 on 2025-08-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='user',
        ),
    ]
